Script started on Tue Mar 27 18:35:13 2018
]0;yuxuaj@klaatu:~[?1034h[yuxuaj@klaatu ~]$ whoami
yuxuaj
]0;yuxuaj@klaatu:~[yuxuaj@klaatu ~]$ echo $SHELL
/bin/bash
]0;yuxuaj@klaatu:~[yuxuaj@klaatu ~]$ pwd
/homes/yuxuaj
]0;yuxuaj@klaatu:~[yuxuaj@klaatu ~]$ uname -a
Linux klaatu.cs.washington.edu 4.9.84-1.el7.retpoline.x86_64 #1 SMP Sun Feb 25 15:56:57 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
]0;yuxuaj@klaatu:~[yuxuaj@klaatu ~]$ cat /etc/redhat-release
CentOS Linux release 7.4.1708 (Core)
]0;yuxuaj@klaatu:~[yuxuaj@klaatu ~]$ gcc --version -std=c11
gcc (GCC) 5.3.1 20160406 (Red Hat 5.3.1-6)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

]0;yuxuaj@klaatu:~[yuxuaj@klaatu ~]$ exit
exit

Script done on Tue Mar 27 18:36:13 2018
